runtime: nodejs12
instance_class: F1

automatic_scaling:
  max_instances: 1
  min_idle_instances: 1
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 50
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt|json|svg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt|json|svg)$
    secure: always

  - url: /.*
    script: auto
    secure: always
